name: Publish ngtools-pyscript on PyPI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Commit / Branch / Tag / SHA to checkout'
        required: false
        default: 'main'
      publish:
        description: 'Publish'
        required: false
        default: 'test+pypi'
        type: choice
        options:
          - 'pypi'
          - 'test'
          - 'test+pypi'
      python-version:
        description: 'Python version'
        required: false
        default: '3.11'

jobs:

  # --------------------------------------------------------------------
  publish-test:
    if: ${{ contains(inputs.publish, 'test') }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment:
      name: testpypi
      url: https://test.pypi.org/p/ngtools-pyscript

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}

      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies for building package
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build
        shell: bash

      - name: Build a binary wheel and a source tarball
        run: |
          python -m build
        shell: bash

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  # --------------------------------------------------------------------
  publish-pypi:
    if: ${{ always() && contains(inputs.publish, 'pypi') }}
    runs-on: ubuntu-latest
    needs: publish-test

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/ngtools-pyscript

    steps:
      - name: Fail early if publish-test failed
        if: ${{ needs.publish-test.result == 'failure' }}
        run: exit 1

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}

      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies for building package
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build
        shell: bash

      - name: Build a binary wheel and a source tarball
        run: |
          python -m build
        shell: bash

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
